Repository falcosecurity/testing, pull requests merged in 2023-12, with the labels that each got.

#35 fix(tests/falco): solve issues with description tests for static builds
  tests/falco/commands_test.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#36 fix(tests/falco): invalid rule names must return error when described
  tests/falco/commands_test.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#34 new(pkg,tests): port falco driver loader tests to use falcoctl.
  pkg/falcodriverloader/tester.go
  pkg/falcodriverloader/tester_options.go
  pkg/falcodriverloader/tester_output.go
  tests/falcodriverloader/drivers_test.go
  tests/tests.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#38 chore(tests/falcodriverloader): avoid falcoctl driver config call.
  tests/falcodriverloader/drivers_test.go
Labels: dco-signoff: yes, approved, size/S, lgtm
