Repository falcosecurity/testing, pull requests merged in 2024-02, with the labels that each got.

#40 new(pkg,tests): alllow to pass Falco config path as argument.
  pkg/falco/tester.go
  tests/falco/commands_test.go
  tests/falco/legacy_test.go
  tests/falco/miscs_test.go
  tests/tests.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#43 fix(pkg/falco): allow back single tests to override used config.
  pkg/falco/tester.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#44 chore: let composite action's caller install kernel headers.
  README.md
  action.yml
Labels: dco-signoff: yes, approved, size/S, lgtm

#30 new(tests/falco): add TestFalco_Config_Metrics_Enabled
  tests/data/configs/configs.go
  tests/falco/config_test.go
Labels: dco-signoff: yes, approved, size/S, lgtm

#45 fix: invalid macro names
  tests/data/rules/falco.go
  tests/falco/legacy_test.go
Labels: dco-signoff: yes, approved, size/S, lgtm
